language: node_js
node_js:
- 10

branches:
  only:
  - master

before_script:
#- npm install -g @vue/cli
#- npm install -g @vue/cli-service-global
- npm install

script:
- npm run lint
- npm run build
deploy:
  provider: surge
  project: ./dist
  domain: test-vue.surge.sh
  token: fe60cd1f3db96547af4d6e045714b048
  skip_cleanup: true
