language: node_js
node_js:
- 10

branches:
  only:
  - master

before_script:
- npm install
- export SURGE_TOKEN=fe60cd1f3db96547af4d6e045714b048

script:
- npm run lint
- npm run build
deploy:
  provider: surge
  project: ./dist
  domain: vue-abdo.surge.sh
  token: fe60cd1f3db96547af4d6e045714b048
  skip_cleanup: true
